# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class XueqiuItem(scrapy.Item):
    symbol = scrapy.Field()
    exchange = scrapy.Field()
    code = scrapy.Field()
    name = scrapy.Field()
    current = scrapy.Field()
    percentage = scrapy.Field()
    change = scrapy.Field()
    open = scrapy.Field()
    high = scrapy.Field()
    low = scrapy.Field()
    close = scrapy.Field()
    last_close = scrapy.Field()
    high52week = scrapy.Field()
    low52week = scrapy.Field()
    rise_count = scrapy.Field()
    flat_count = scrapy.Field()
    fall_count = scrapy.Field()
    marketCapital = scrapy.Field()
    market_status = scrapy.Field()
    lot_volume = scrapy.Field()
    amount = scrapy.Field()
    utc_time = scrapy.Field()
    currency_unit = scrapy.Field()
    rise_stop = scrapy.Field()
    fall_stop = scrapy.Field()
    beta = scrapy.Field()


class UsNewStock(scrapy.Item):
    symbol = scrapy.Field()
    company_name = scrapy.Field()
    ipo_date = scrapy.Field()
    shares = scrapy.Field()
    ipo_price = scrapy.Field()
    close = scrapy.Field()
    chg = scrapy.Field()
    percent = scrapy.Field()

    totalShares = scrapy.Field()
    lot_volume = scrapy.Field()
    open = scrapy.Field()
    high = scrapy.Field()
    high52week = scrapy.Field()
    low52week = scrapy.Field()
    low = scrapy.Field()
    amplitude = scrapy.Field()
    turnover_rate = scrapy.Field()
    last_close = scrapy.Field()
    marketCapital = scrapy.Field()

    introduction = scrapy.Field()
    official_website = scrapy.Field()
    document = scrapy.Field()

    utc_time = scrapy.Field()


class ShNewStock(scrapy.Item):
    symbol = scrapy.Field()
    name = scrapy.Field()
    onl_subcode = scrapy.Field()
    list_date = scrapy.Field()
    actissqty = scrapy.Field()
    onl_actissqty = scrapy.Field()
    onl_submaxqty = scrapy.Field()
    onl_subbegdate = scrapy.Field()
    onl_unfrozendate = scrapy.Field()
    onl_refunddate = scrapy.Field()
    iss_price = scrapy.Field()
    onl_frozenamt = scrapy.Field()
    onl_lotwinrt = scrapy.Field()
    onl_lorwincode = scrapy.Field()
    onl_lotwiner_stpub_date = scrapy.Field()
    onl_effsubqty = scrapy.Field()
    onl_effsubnum = scrapy.Field()
    onl_onversubrt = scrapy.Field()
    offl_lotwinrt = scrapy.Field()
    offl_effsubqty = scrapy.Field()
    offl_planum = scrapy.Field()
    offl_oversubrt = scrapy.Field()
    napsaft = scrapy.Field()
    eps_dilutedaft = scrapy.Field()
    leaduwer = scrapy.Field()
    list_recomer = scrapy.Field()
    acttotraiseamt = scrapy.Field()
    onl_rdshowweb = scrapy.Field()
    onl_rdshowbegdate = scrapy.Field()
    onl_distrdate = scrapy.Field()
    onl_drawlotsdate = scrapy.Field()
    first_open_price = scrapy.Field()
    first_close_price = scrapy.Field()
    first_percent = scrapy.Field()
    first_turnrate = scrapy.Field()
    stock_income = scrapy.Field()
    onl_lotwin_amount = scrapy.Field()
    listed_percent = scrapy.Field()
    current = scrapy.Field()
    pe_ttm = scrapy.Field()
    pb = scrapy.Field()
    percent = scrapy.Field()
    hasexist = scrapy.Field()
    utc_time = scrapy.Field()